# Generated by Django 3.2.13 on 2022-05-27 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_off', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер скидки')),
                ('currency', models.CharField(default='usd', max_length=3, verbose_name='Валюта')),
                ('duration', models.CharField(choices=[('O', 'once'), ('R', 'repeated'), ('F', 'forever')], default='O', max_length=1)),
                ('duration_in_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок действия скидки')),
                ('percent_off', models.PositiveIntegerField(blank=True, null=True, verbose_name='Процент скидки')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Дата исполнения')),
                ('status', models.CharField(choices=[('OPN', 'open'), ('SBM', 'submitted'), ('PRS', 'processing'), ('CMP', 'complete'), ('CNL', 'canceled')], default='OPN', max_length=3, verbose_name='Статус заказа')),
                ('amount_total', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_list', to='api.item', verbose_name='Товары')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='api.order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Срок окончания действия')),
                ('date_applied', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования купона')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coupon', verbose_name='Купон')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='api.order', verbose_name='Скидки')),
            ],
        ),
    ]
