# Generated by Django 3.2.13 on 2022-05-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220527_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_total',
        ),
    ]
